services:
  scoresync:
    build:
      context: .
      dockerfile: Dockerfile
    image: ghcr.io/${GITHUB_REPOSITORY_OWNER:-piliman22}/scoresync:local
    container_name: scoresync
    ports:
      - "3939:3939"
    volumes:
      - ./levels:/app/levels
    restart: unless-stopped